//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cSharp.wsTesoreria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsTesoreria.ITesoreria")]
    public interface ITesoreria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarBancos", ReplyAction="http://tempuri.org/ITesoreria/GuardarBancosResponse")]
        cSharp.wsTesoreria.GuardarBancosResponse GuardarBancos(cSharp.wsTesoreria.GuardarBancosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarBancos", ReplyAction="http://tempuri.org/ITesoreria/GuardarBancosResponse")]
        System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarBancosResponse> GuardarBancosAsync(cSharp.wsTesoreria.GuardarBancosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarAntiguedadCXC", ReplyAction="http://tempuri.org/ITesoreria/GuardarAntiguedadCXCResponse")]
        cSharp.wsTesoreria.GuardarAntiguedadCXCResponse GuardarAntiguedadCXC(cSharp.wsTesoreria.GuardarAntiguedadCXCRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarAntiguedadCXC", ReplyAction="http://tempuri.org/ITesoreria/GuardarAntiguedadCXCResponse")]
        System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarAntiguedadCXCResponse> GuardarAntiguedadCXCAsync(cSharp.wsTesoreria.GuardarAntiguedadCXCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarInventario", ReplyAction="http://tempuri.org/ITesoreria/GuardarInventarioResponse")]
        cSharp.wsTesoreria.GuardarInventarioResponse GuardarInventario(cSharp.wsTesoreria.GuardarInventarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarInventario", ReplyAction="http://tempuri.org/ITesoreria/GuardarInventarioResponse")]
        System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarInventarioResponse> GuardarInventarioAsync(cSharp.wsTesoreria.GuardarInventarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarImpuesto", ReplyAction="http://tempuri.org/ITesoreria/GuardarImpuestoResponse")]
        cSharp.wsTesoreria.GuardarImpuestoResponse GuardarImpuesto(cSharp.wsTesoreria.GuardarImpuestoRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarImpuesto", ReplyAction="http://tempuri.org/ITesoreria/GuardarImpuestoResponse")]
        System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarImpuestoResponse> GuardarImpuestoAsync(cSharp.wsTesoreria.GuardarImpuestoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarTipoCambio", ReplyAction="http://tempuri.org/ITesoreria/GuardarTipoCambioResponse")]
        cSharp.wsTesoreria.GuardarTipoCambioResponse GuardarTipoCambio(cSharp.wsTesoreria.GuardarTipoCambioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/GuardarTipoCambio", ReplyAction="http://tempuri.org/ITesoreria/GuardarTipoCambioResponse")]
        System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarTipoCambioResponse> GuardarTipoCambioAsync(cSharp.wsTesoreria.GuardarTipoCambioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/Init", ReplyAction="http://tempuri.org/ITesoreria/InitResponse")]
        cSharp.wsTesoreria.InitResponse Init(cSharp.wsTesoreria.InitRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITesoreria/Init", ReplyAction="http://tempuri.org/ITesoreria/InitResponse")]
        System.Threading.Tasks.Task<cSharp.wsTesoreria.InitResponse> InitAsync(cSharp.wsTesoreria.InitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarBancos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarBancosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Banco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short Moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CuentaCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string nombreCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public decimal Disponible;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public System.DateTime FechaSaldo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int IdCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string TOKEN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string Mensaje;
        
        public GuardarBancosRequest() {
        }
        
        public GuardarBancosRequest(string Banco, short Moneda, string CuentaCliente, string nombreCuenta, decimal Disponible, string Tipo, System.DateTime FechaSaldo, int IdCompania, string TOKEN, string Mensaje) {
            this.Banco = Banco;
            this.Moneda = Moneda;
            this.CuentaCliente = CuentaCliente;
            this.nombreCuenta = nombreCuenta;
            this.Disponible = Disponible;
            this.Tipo = Tipo;
            this.FechaSaldo = FechaSaldo;
            this.IdCompania = IdCompania;
            this.TOKEN = TOKEN;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarBancosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarBancosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GuardarBancosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Mensaje;
        
        public GuardarBancosResponse() {
        }
        
        public GuardarBancosResponse(bool GuardarBancosResult, string Mensaje) {
            this.GuardarBancosResult = GuardarBancosResult;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarAntiguedadCXC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarAntiguedadCXCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public short IdCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string NombreCliene;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public short Moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CuentaCXC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public short Diascredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.DateTime FechaDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public System.DateTime FechaVencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public decimal MontoOriginal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public decimal Sinvencer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public decimal De1A30;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal De31A60;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public decimal De61A90;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public decimal Mas90;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string Tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string TOKEN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string Mensaje;
        
        public GuardarAntiguedadCXCRequest() {
        }
        
        public GuardarAntiguedadCXCRequest(
                    short IdCompania, 
                    string NombreCliene, 
                    short Moneda, 
                    string CuentaCXC, 
                    short Diascredito, 
                    System.DateTime FechaDocumento, 
                    System.DateTime FechaVencimiento, 
                    decimal MontoOriginal, 
                    decimal Sinvencer, 
                    decimal De1A30, 
                    decimal De31A60, 
                    decimal De61A90, 
                    decimal Mas90, 
                    string Tipo, 
                    string TOKEN, 
                    string Mensaje) {
            this.IdCompania = IdCompania;
            this.NombreCliene = NombreCliene;
            this.Moneda = Moneda;
            this.CuentaCXC = CuentaCXC;
            this.Diascredito = Diascredito;
            this.FechaDocumento = FechaDocumento;
            this.FechaVencimiento = FechaVencimiento;
            this.MontoOriginal = MontoOriginal;
            this.Sinvencer = Sinvencer;
            this.De1A30 = De1A30;
            this.De31A60 = De31A60;
            this.De61A90 = De61A90;
            this.Mas90 = Mas90;
            this.Tipo = Tipo;
            this.TOKEN = TOKEN;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarAntiguedadCXCResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarAntiguedadCXCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GuardarAntiguedadCXCResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Mensaje;
        
        public GuardarAntiguedadCXCResponse() {
        }
        
        public GuardarAntiguedadCXCResponse(bool GuardarAntiguedadCXCResult, string Mensaje) {
            this.GuardarAntiguedadCXCResult = GuardarAntiguedadCXCResult;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarInventario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarInventarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public short IdCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Area;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Familia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string articulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string articulodescripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string boleta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public System.DateTime Fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public short Permanencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public decimal Saldo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public decimal ventasAnuales;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public decimal Peso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public decimal Costo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string TOKEN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string Mensaje;
        
        public GuardarInventarioRequest() {
        }
        
        public GuardarInventarioRequest(
                    short IdCompania, 
                    string sector, 
                    string Area, 
                    string Familia, 
                    string Cliente, 
                    string articulo, 
                    string articulodescripcion, 
                    string boleta, 
                    System.DateTime Fecha, 
                    short Permanencia, 
                    decimal Saldo, 
                    decimal ventasAnuales, 
                    decimal Peso, 
                    decimal Costo, 
                    string TOKEN, 
                    string Mensaje) {
            this.IdCompania = IdCompania;
            this.sector = sector;
            this.Area = Area;
            this.Familia = Familia;
            this.Cliente = Cliente;
            this.articulo = articulo;
            this.articulodescripcion = articulodescripcion;
            this.boleta = boleta;
            this.Fecha = Fecha;
            this.Permanencia = Permanencia;
            this.Saldo = Saldo;
            this.ventasAnuales = ventasAnuales;
            this.Peso = Peso;
            this.Costo = Costo;
            this.TOKEN = TOKEN;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarInventarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarInventarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GuardarInventarioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Mensaje;
        
        public GuardarInventarioResponse() {
        }
        
        public GuardarInventarioResponse(bool GuardarInventarioResult, string Mensaje) {
            this.GuardarInventarioResult = GuardarInventarioResult;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarImpuesto", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarImpuestoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public short IdCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string CuentaImpuesto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public short IdClasificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public decimal Monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string TOKEN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Mensaje;
        
        public GuardarImpuestoRequest() {
        }
        
        public GuardarImpuestoRequest(short IdCompania, string CuentaImpuesto, short IdClasificacion, decimal Monto, string Descripcion, string TOKEN, string Mensaje) {
            this.IdCompania = IdCompania;
            this.CuentaImpuesto = CuentaImpuesto;
            this.IdClasificacion = IdClasificacion;
            this.Monto = Monto;
            this.Descripcion = Descripcion;
            this.TOKEN = TOKEN;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarImpuestoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarImpuestoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GuardarImpuestoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Mensaje;
        
        public GuardarImpuestoResponse() {
        }
        
        public GuardarImpuestoResponse(bool GuardarImpuestoResult, string Mensaje) {
            this.GuardarImpuestoResult = GuardarImpuestoResult;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarTipoCambio", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarTipoCambioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal TipoCambioCompra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal TipoCambioVenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public short Moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string TOKEN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Mensaje;
        
        public GuardarTipoCambioRequest() {
        }
        
        public GuardarTipoCambioRequest(decimal TipoCambioCompra, decimal TipoCambioVenta, short Moneda, string TOKEN, string Mensaje) {
            this.TipoCambioCompra = TipoCambioCompra;
            this.TipoCambioVenta = TipoCambioVenta;
            this.Moneda = Moneda;
            this.TOKEN = TOKEN;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuardarTipoCambioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuardarTipoCambioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GuardarTipoCambioResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Mensaje;
        
        public GuardarTipoCambioResponse() {
        }
        
        public GuardarTipoCambioResponse(bool GuardarTipoCambioResult, string Mensaje) {
            this.GuardarTipoCambioResult = GuardarTipoCambioResult;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Init", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Contrasena;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public short IdCompania;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string TOKEN;
        
        public InitRequest() {
        }
        
        public InitRequest(string Usuario, string Contrasena, short IdCompania, string TOKEN) {
            this.Usuario = Usuario;
            this.Contrasena = Contrasena;
            this.IdCompania = IdCompania;
            this.TOKEN = TOKEN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InitResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool InitResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string TOKEN;
        
        public InitResponse() {
        }
        
        public InitResponse(bool InitResult, string TOKEN) {
            this.InitResult = InitResult;
            this.TOKEN = TOKEN;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITesoreriaChannel : cSharp.wsTesoreria.ITesoreria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TesoreriaClient : System.ServiceModel.ClientBase<cSharp.wsTesoreria.ITesoreria>, cSharp.wsTesoreria.ITesoreria {
        
        public TesoreriaClient() {
        }
        
        public TesoreriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TesoreriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesoreriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesoreriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cSharp.wsTesoreria.GuardarBancosResponse cSharp.wsTesoreria.ITesoreria.GuardarBancos(cSharp.wsTesoreria.GuardarBancosRequest request) {
            return base.Channel.GuardarBancos(request);
        }
        
        public bool GuardarBancos(string Banco, short Moneda, string CuentaCliente, string nombreCuenta, decimal Disponible, string Tipo, System.DateTime FechaSaldo, int IdCompania, string TOKEN, ref string Mensaje) {
            cSharp.wsTesoreria.GuardarBancosRequest inValue = new cSharp.wsTesoreria.GuardarBancosRequest();
            inValue.Banco = Banco;
            inValue.Moneda = Moneda;
            inValue.CuentaCliente = CuentaCliente;
            inValue.nombreCuenta = nombreCuenta;
            inValue.Disponible = Disponible;
            inValue.Tipo = Tipo;
            inValue.FechaSaldo = FechaSaldo;
            inValue.IdCompania = IdCompania;
            inValue.TOKEN = TOKEN;
            inValue.Mensaje = Mensaje;
            cSharp.wsTesoreria.GuardarBancosResponse retVal = ((cSharp.wsTesoreria.ITesoreria)(this)).GuardarBancos(inValue);
            Mensaje = retVal.Mensaje;
            return retVal.GuardarBancosResult;
        }
        
        public System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarBancosResponse> GuardarBancosAsync(cSharp.wsTesoreria.GuardarBancosRequest request) {
            return base.Channel.GuardarBancosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cSharp.wsTesoreria.GuardarAntiguedadCXCResponse cSharp.wsTesoreria.ITesoreria.GuardarAntiguedadCXC(cSharp.wsTesoreria.GuardarAntiguedadCXCRequest request) {
            return base.Channel.GuardarAntiguedadCXC(request);
        }
        
        public bool GuardarAntiguedadCXC(
                    short IdCompania, 
                    string NombreCliene, 
                    short Moneda, 
                    string CuentaCXC, 
                    short Diascredito, 
                    System.DateTime FechaDocumento, 
                    System.DateTime FechaVencimiento, 
                    decimal MontoOriginal, 
                    decimal Sinvencer, 
                    decimal De1A30, 
                    decimal De31A60, 
                    decimal De61A90, 
                    decimal Mas90, 
                    string Tipo, 
                    string TOKEN, 
                    ref string Mensaje) {
            cSharp.wsTesoreria.GuardarAntiguedadCXCRequest inValue = new cSharp.wsTesoreria.GuardarAntiguedadCXCRequest();
            inValue.IdCompania = IdCompania;
            inValue.NombreCliene = NombreCliene;
            inValue.Moneda = Moneda;
            inValue.CuentaCXC = CuentaCXC;
            inValue.Diascredito = Diascredito;
            inValue.FechaDocumento = FechaDocumento;
            inValue.FechaVencimiento = FechaVencimiento;
            inValue.MontoOriginal = MontoOriginal;
            inValue.Sinvencer = Sinvencer;
            inValue.De1A30 = De1A30;
            inValue.De31A60 = De31A60;
            inValue.De61A90 = De61A90;
            inValue.Mas90 = Mas90;
            inValue.Tipo = Tipo;
            inValue.TOKEN = TOKEN;
            inValue.Mensaje = Mensaje;
            cSharp.wsTesoreria.GuardarAntiguedadCXCResponse retVal = ((cSharp.wsTesoreria.ITesoreria)(this)).GuardarAntiguedadCXC(inValue);
            Mensaje = retVal.Mensaje;
            return retVal.GuardarAntiguedadCXCResult;
        }
        
        public System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarAntiguedadCXCResponse> GuardarAntiguedadCXCAsync(cSharp.wsTesoreria.GuardarAntiguedadCXCRequest request) {
            return base.Channel.GuardarAntiguedadCXCAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cSharp.wsTesoreria.GuardarInventarioResponse cSharp.wsTesoreria.ITesoreria.GuardarInventario(cSharp.wsTesoreria.GuardarInventarioRequest request) {
            return base.Channel.GuardarInventario(request);
        }
        
        public bool GuardarInventario(
                    short IdCompania, 
                    string sector, 
                    string Area, 
                    string Familia, 
                    string Cliente, 
                    string articulo, 
                    string articulodescripcion, 
                    string boleta, 
                    System.DateTime Fecha, 
                    short Permanencia, 
                    decimal Saldo, 
                    decimal ventasAnuales, 
                    decimal Peso, 
                    decimal Costo, 
                    string TOKEN, 
                    ref string Mensaje) {
            cSharp.wsTesoreria.GuardarInventarioRequest inValue = new cSharp.wsTesoreria.GuardarInventarioRequest();
            inValue.IdCompania = IdCompania;
            inValue.sector = sector;
            inValue.Area = Area;
            inValue.Familia = Familia;
            inValue.Cliente = Cliente;
            inValue.articulo = articulo;
            inValue.articulodescripcion = articulodescripcion;
            inValue.boleta = boleta;
            inValue.Fecha = Fecha;
            inValue.Permanencia = Permanencia;
            inValue.Saldo = Saldo;
            inValue.ventasAnuales = ventasAnuales;
            inValue.Peso = Peso;
            inValue.Costo = Costo;
            inValue.TOKEN = TOKEN;
            inValue.Mensaje = Mensaje;
            cSharp.wsTesoreria.GuardarInventarioResponse retVal = ((cSharp.wsTesoreria.ITesoreria)(this)).GuardarInventario(inValue);
            Mensaje = retVal.Mensaje;
            return retVal.GuardarInventarioResult;
        }
        
        public System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarInventarioResponse> GuardarInventarioAsync(cSharp.wsTesoreria.GuardarInventarioRequest request) {
            return base.Channel.GuardarInventarioAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cSharp.wsTesoreria.GuardarImpuestoResponse cSharp.wsTesoreria.ITesoreria.GuardarImpuesto(cSharp.wsTesoreria.GuardarImpuestoRequest request) {
            return base.Channel.GuardarImpuesto(request);
        }
        
        public bool GuardarImpuesto(short IdCompania, string CuentaImpuesto, short IdClasificacion, decimal Monto, string Descripcion, string TOKEN, ref string Mensaje) {
            cSharp.wsTesoreria.GuardarImpuestoRequest inValue = new cSharp.wsTesoreria.GuardarImpuestoRequest();
            inValue.IdCompania = IdCompania;
            inValue.CuentaImpuesto = CuentaImpuesto;
            inValue.IdClasificacion = IdClasificacion;
            inValue.Monto = Monto;
            inValue.Descripcion = Descripcion;
            inValue.TOKEN = TOKEN;
            inValue.Mensaje = Mensaje;
            cSharp.wsTesoreria.GuardarImpuestoResponse retVal = ((cSharp.wsTesoreria.ITesoreria)(this)).GuardarImpuesto(inValue);
            Mensaje = retVal.Mensaje;
            return retVal.GuardarImpuestoResult;
        }
        
        public System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarImpuestoResponse> GuardarImpuestoAsync(cSharp.wsTesoreria.GuardarImpuestoRequest request) {
            return base.Channel.GuardarImpuestoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cSharp.wsTesoreria.GuardarTipoCambioResponse cSharp.wsTesoreria.ITesoreria.GuardarTipoCambio(cSharp.wsTesoreria.GuardarTipoCambioRequest request) {
            return base.Channel.GuardarTipoCambio(request);
        }
        
        public bool GuardarTipoCambio(decimal TipoCambioCompra, decimal TipoCambioVenta, short Moneda, string TOKEN, ref string Mensaje) {
            cSharp.wsTesoreria.GuardarTipoCambioRequest inValue = new cSharp.wsTesoreria.GuardarTipoCambioRequest();
            inValue.TipoCambioCompra = TipoCambioCompra;
            inValue.TipoCambioVenta = TipoCambioVenta;
            inValue.Moneda = Moneda;
            inValue.TOKEN = TOKEN;
            inValue.Mensaje = Mensaje;
            cSharp.wsTesoreria.GuardarTipoCambioResponse retVal = ((cSharp.wsTesoreria.ITesoreria)(this)).GuardarTipoCambio(inValue);
            Mensaje = retVal.Mensaje;
            return retVal.GuardarTipoCambioResult;
        }
        
        public System.Threading.Tasks.Task<cSharp.wsTesoreria.GuardarTipoCambioResponse> GuardarTipoCambioAsync(cSharp.wsTesoreria.GuardarTipoCambioRequest request) {
            return base.Channel.GuardarTipoCambioAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cSharp.wsTesoreria.InitResponse cSharp.wsTesoreria.ITesoreria.Init(cSharp.wsTesoreria.InitRequest request) {
            return base.Channel.Init(request);
        }
        
        public bool Init(string Usuario, string Contrasena, short IdCompania, ref string TOKEN) {
            cSharp.wsTesoreria.InitRequest inValue = new cSharp.wsTesoreria.InitRequest();
            inValue.Usuario = Usuario;
            inValue.Contrasena = Contrasena;
            inValue.IdCompania = IdCompania;
            inValue.TOKEN = TOKEN;
            cSharp.wsTesoreria.InitResponse retVal = ((cSharp.wsTesoreria.ITesoreria)(this)).Init(inValue);
            TOKEN = retVal.TOKEN;
            return retVal.InitResult;
        }
        
        public System.Threading.Tasks.Task<cSharp.wsTesoreria.InitResponse> InitAsync(cSharp.wsTesoreria.InitRequest request) {
            return base.Channel.InitAsync(request);
        }
    }
}
